export NEW_CLI=1 
export MyTenant=yyyy.jzq02463.live.dynatrace.com
export MyToken=dt0c01.abcdefghij.abcdefghijklmn
export PaasToken=dt0c01.abcdefghij.abcdefghijklmn
export list_user="user00@demo.com user01@demo.com"
export EnableSynthetic=false
export TIME=`date +%Y%m%d%H%M%S`
export DOMAIN_NAME_DEFAULT=dynatracelab$TIME
export DOMAIN_NAME=$DOMAIN_NAME_DEFAULT
export PASSWORD=Dynatrace@2022
export SIZE_LINUX=Standard_B2ms #2 CPU 8 GB
export SIZE_WINDOWS=Standard_B2ms   #2 CPU 8 GB
export LOCATION1=francecentral
export LOCATION2=westeurope
export LOCATION3=northeurope
export LOCATION4=uksouth
export LOCATION5=eastus #Reserved for the kubernetes lab
export LOCATION6=eastus2 #Reserved for the kubernetes lab
export START_ENV=0
export NBENV=2
