config:
#- clickpath-1: lab-click-path.json
- clickpath-2: angular-clickpath.json
- httpmonitor-1: lab-http-monitor.json

clickpath-1:
- name: "{{.Env.Appname}}-clickpath classic"
- url: "http://{{.Env.Hostname}}"
- mz: "{{.Env.Appname}}"
- enable: "{{.Env.EnableSynthetic}}"
- applicationId: "/application-web/app-1.id"

clickpath-2:
- name: "{{.Env.Appname}}-clickpath angular"
- url: "http://{{.Env.Hostname}}:9079"
- mz: "{{.Env.Appname}}"
- enable: "{{.Env.EnableSynthetic}}"
- applicationId: "/application-web/app-1.id"

httpmonitor-1:
- name: "{{.Env.Appname}}-httpmonitor"
- url: "http://{{.Env.Hostname}}"
- mz: "{{.Env.Appname}}"
- enable: "{{.Env.EnableSynthetic}}"
- applicationId: "/application-web/app-1.id"
